In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('clean_googleplaystore_user_reviews.csv')


df_n = pd.read_excel('C:/Users/DBSOM-L490-24/Documents/DEVELHOPE/PYTHON/data-5---team-4/Stage_2/Data/n.xlsx')
df_p = pd.read_excel('C:/Users/DBSOM-L490-24/Documents/DEVELHOPE/PYTHON/data-5---team-4/Stage_2/Data/p.xlsx')

print(f'the shape of n is {df_n.shape}')
print(f'the shape of p is {df_p.shape}')
print(f'the shape of df_review is {df.shape}')

the shape of n is (4782, 1)
the shape of p is (2004, 1)
the shape of df_review is (41710, 2)

In [9]:
import re
import string


def sent_cat(data):
    if data > 0:
        return "positive"
    elif data < 0:
        return "negative"
    else:
        return "neutral"
    
def sen_p(data):
    sent_scor = 0
    for positive in df_p.itertuples():
        if positive[0] in data:
            sent_scor += 1
    for negative in df_n.itertuples():
        if positive[0] in data:
            sent_scor -= 1
    return sent_scor      
        
def filt_str(row):
    return re.sub('['+re.escape(string.punctuation)+']', '',row)

df['Translated_Reviews']= df['Translated_Review'].apply(lambda row : filt_str(row).lower())

#df['Sentimental_Score']=df['Translated_Review'].apply(lambda row : sen_p(list(row) ))

#df_review['Sentimental_Cat']=df_review['Translated_Review'].apply(lambda row : sent_cat(row))

df

,App,Translated_Review,Translated_Reviews
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,i like eat delicious food thats im cooking foo...
1,10 Best Foods for You,This help eating healthy exercise regular basis,this help eating healthy exercise regular basis
2,10 Best Foods for You,NOREVIEW,noreview
3,10 Best Foods for You,Works great especially going grocery store,works great especially going grocery store
4,10 Best Foods for You,Best idea us,best idea us
...,...,...,...
41705,Housing-Real Estate & Property,NOREVIEW,noreview
41706,Housing-Real Estate & Property,NOREVIEW,noreview
41707,Housing-Real Estate & Property,NOREVIEW,noreview
41708,Housing-Real Estate & Property,NOREVIEW,noreview
41709,Housing-Real Estate & Property,NOREVIEW,noreview

In [8]:
df

,App,Translated_Review,Translated_Reviews
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,I like eat delicious food Thats Im cooking foo...
1,10 Best Foods for You,This help eating healthy exercise regular basis,This help eating healthy exercise regular basis
2,10 Best Foods for You,NOREVIEW,NOREVIEW
3,10 Best Foods for You,Works great especially going grocery store,Works great especially going grocery store
4,10 Best Foods for You,Best idea us,Best idea us
...,...,...,...
41705,Housing-Real Estate & Property,NOREVIEW,NOREVIEW
41706,Housing-Real Estate & Property,NOREVIEW,NOREVIEW
41707,Housing-Real Estate & Property,NOREVIEW,NOREVIEW
41708,Housing-Real Estate & Property,NOREVIEW,NOREVIEW
41709,Housing-Real Estate & Property,NOREVIEW,NOREVIEW