# Import numpy,Pandas and Matplotlib

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("C:/Users/DBSOM-L490-24/Documents/DEVELHOPE/PYTHON/data-5---team-4/Stage_2/Data/cleaned_googleplaystore.csv")
df

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.00,10000,Free,0.0,Everyone,Art & Design
1,1,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.70,5000000,Free,0.0,Everyone,Art & Design
2,2,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.00,50000000,Free,0.0,Teen,Art & Design
3,3,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.80,100000,Free,0.0,Everyone,Art & Design;Creativity
4,4,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.60,50000,Free,0.0,Everyone,Art & Design
...,...,...,...,...,...,...,...,...,...,...,...
8192,8192,FR Calculator,FAMILY,4.0,7,2.60,500,Free,0.0,Everyone,Education
8193,8193,Sya9a Maroc - FR,FAMILY,4.5,38,53.00,5000,Free,0.0,Everyone,Education
8194,8194,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.60,100,Free,0.0,Everyone,Education
8195,8195,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,-99.99,1000,Free,0.0,Mature 17+,Books & Reference
8196,8196,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.00,10000000,Free,0.0,Everyone,Lifestyle

# Converting series to dataframe

In [3]:
df['App'].to_frame()

                                                    App
0        Photo Editor & Candy Camera & Grid & ScrapBook
1     U Launcher Lite – FREE Live Cool Themes, Hide ...
2                                 Sketch - Draw & Paint
3                 Pixel Draw - Number Art Coloring Book
4                            Paper flowers instructions
...                                                 ...
8192                                      FR Calculator
8193                                   Sya9a Maroc - FR
8194                   Fr. Mike Schmitz Audio Teachings
8195                      The SCP Foundation DB fr nn5n
8196      iHoroscope - 2018 Daily Horoscope & Astrology

[8197 rows x 1 columns]

# Features of Data

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8197 entries, 0 to 8196
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      8197 non-null   int64
 1   App             8197 non-null   object
 2   Category        8197 non-null   object
 3   Rating          8197 non-null   float64
 4   Reviews         8197 non-null   int64
 5   Size            8197 non-null   float64
 6   Installs        8197 non-null   int64
 7   Type            8197 non-null   object
 8   Price           8197 non-null   float64
 9   Content Rating  8197 non-null   object
 10  Genres          8197 non-null   object
dtypes: float64(3), int64(3), object(5)
memory usage: 704.6+ KB